#!/bin/bash

set -e

BLUE='\033[0;34m'
UNDERLINE='\033[0;4m'
RESET='\033[0m'

echo -e "-----------------------------------------"
echo -e "                                         "
echo -e "  Thank you for installing ${BLUE}Grouparoo${RESET}!"
echo -e "  You can learn more @ ${UNDERLINE}www.grouparoo.com${RESET} "
echo -e "                                         "
echo -e "  🦘                                     "
echo -e "                                         "
echo -e "-----------------------------------------"
echo -e "                                         "
