#!/usr/bin/env bash

# set -e

cd "`dirname "$0"`/.."
PROJECT_PATH="`pwd`"
source ./../../tools/shared/max_bg_procs

CLI="$PROJECT_PATH/../../cli/dist/grouparoo.js"

# Set needed ENV
export REDIS_URL="redis://mock"
export DATABASE_URL="sqlite://grouparoo_test.sqlite"
export SERVER_TOKEN="ABC123"
export WORKERS=1

printf "*** Starting Tests ***\r\n"

OUTPUT_HELP=`$CLI --help`
printf "help flag"
if [[ "$OUTPUT_HELP" == *"Learn more at https://www.grouparoo.com/docs"* && \
      "$OUTPUT_HELP" != *"Don't see the commands that you are looking for?"* ]]; then
    printf " ✅\r\n"
else
    printf " 🚫\r\n"
    exit 1
fi

cd "../"

OUTPUT_HELP=`$CLI --help`
printf "help flag outside project dir"
if [[ "$OUTPUT_HELP" == *"Learn more at https://www.grouparoo.com/docs"* && \
      "$OUTPUT_HELP" == *"Don't see the commands that you are looking for?"* ]]; then
    printf " ✅\r\n"
else
    printf " 🚫\r\n"
    exit 1
fi

cd $PROJECT_PATH

OUTPUT_VALIDATE=`$CLI validate`
printf "validate"
if [[ "$OUTPUT_VALIDATE" == *"Validation succeeded"*  ]]; then
    printf " ✅\r\n"
else
    printf " 🚫\r\n"
    exit 1
fi

OUTPUT_APPLY=`$CLI apply`
printf "apply"
if [[ "$OUTPUT_APPLY" == *"Config applied"*  ]]; then
    printf " ✅\r\n"
else
    printf " 🚫\r\n"
    exit 1
fi
