#!/usr/bin/env bash

set -e

cd "`dirname "$0"`/.."

# Set needed ENV
export REDIS_URL="redis://mock"
export DATABASE_URL="sqlite://grouparoo_test.sqlite"
export SERVER_TOKEN="ABC123"
export PORT="3000"
export WEB_SERVER="true"

printf "*** Starting Server ***\r\n"
npm run start &

sleep 10

printf "*** checking status ***\r\n"
curl http://localhost:3000/api/v1/status/public
curl http://localhost:3000/api/v1/status/private

printf "It worked!\r\n"
pkill -f dist/grouparoo
wait

printf "Done!\r\n"
