name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install --unsafe-perm
      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */node_modules
            */*/node_modules
            */*/*/node_modules
            dist
            */dist
            */*/dist
            */*/*/dist
            core/web/.next
          key: ${{ runner.os }}-cache-${{ github.sha }}

  license-checker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */node_modules
            */*/node_modules
            */*/*/node_modules
            dist
            */dist
            */*/dist
            */*/*/dist
            core/web/.next
          key: ${{ runner.os }}-cache-${{ github.sha }}
      - run: npm run license-checker

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */node_modules
            */*/node_modules
            */*/*/node_modules
            dist
            */dist
            */*/dist
            */*/*/dist
            core/web/.next
          key: ${{ runner.os }}-cache-${{ github.sha }}
      - run: npm run lint

  test-core-api:
    runs-on: ubuntu-latest
    needs: build

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */node_modules
            */*/node_modules
            */*/*/node_modules
            dist
            */dist
            */*/dist
            */*/*/dist
            core/web/.next
          key: ${{ runner.os }}-cache-${{ github.sha }}
      - run: sudo apt-get update
      - run: sudo apt install -y postgresql-client
      - run: cd core/api && ./bin/create_test_databases
      - run: cd core && npm run test-api
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
          REDIS_URL: redis://localhost:6379/0
          maxMemoryAlloted: 1000

  test-core-web:
    runs-on: ubuntu-latest
    needs: build

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

      redis:
        image: redis
        ports:
          - 6379:6379

      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */node_modules
            */*/node_modules
            */*/*/node_modules
            dist
            */dist
            */*/dist
            */*/*/dist
            core/web/.next
          key: ${{ runner.os }}-cache-${{ github.sha }}
      - run: sudo apt-get update
      - run: sudo apt install -y postgresql-client
      - run: cd core/api && ./bin/create_test_databases
      - name: Get IP Address
        run: echo '::set-env name=SELENIUM_TEST_HOST::`hostname -I`'
      - run: "cd core && npm run test-web"
        env:
          TEST_LOG_LEVEL: info
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
          REDIS_URL: redis://localhost:6379/0
          # SELENIUM_TEST_HOST: $HOST_IP_ADDRESS
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
          maxMemoryAlloted: 1000
      # - name: Setup tmate session
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v2

  test-plugins:
    runs-on: ubuntu-latest
    needs: build

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

      mysql:
        image: mysql:5
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: grouparoo_test
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"

      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */node_modules
            */*/node_modules
            */*/*/node_modules
            dist
            */dist
            */*/dist
            */*/*/dist
            core/web/.next
          key: ${{ runner.os }}-cache-${{ github.sha }}
      - run: sudo apt-get update
      - run: sudo apt install -y postgresql-client
      - run: cd core/api && ./bin/create_test_databases
      - run: ./node_modules/.bin/lerna exec jest --stream --concurrency 1 --ignore "@grouparoo/core" --ignore "*/app-*" -- --ci --passWithNoTests --runInBand
        env:
          TEST_LOG_LEVEL: info
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
          REDIS_URL: redis://localhost:6379/0
          maxMemoryAlloted: 1000
      # - name: Setup tmate session
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v2

  complete:
    runs-on: ubuntu-latest
    needs:
      - build
      - license-checker
      - lint
      - test-core-web
      - test-core-api
      - test-plugins
    steps:
      - run: echo "Done!"
